# https://docs.docker.com/compose/compose-file/05-services/
services:
  # https://github.com/cao7113/hello-phx-api-only/pkgs/container/hello-phx-api-only
  api:
    image: ghcr.io/cao7113/hello-phx-api-only
    # build: .
    environment:
      # MIX_ENV: "prod"
      SECRET_KEY_BASE: "xxx-mock-secret-key-base"
    # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
    healthcheck:
      test: bin/hi pid || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s

  # https://hub.docker.com/r/curlimages/curl/tags
  curl:
    image: curlimages/curl:8.8.0
    depends_on:
      api:
        condition: service_healthy
    command: >
      sh -c "
        # echo
        # ping -c 3 api
        echo
        echo ping api
        curl -sSL http://api:4000/ping
        echo
        echo get build info
        curl -sSL http://api:4000/
      "

  # tool:
  #   image: busybox
  #   depends_on:
  #     api:
  #       condition: service_healthy
  #   command: >
  #     sh -c "
  #       # echo
  #       # ping -c 3 api
  #       echo
  #       echo ping api at port 4000
  #       wget -qO- http://api:4000/ping
  #     "
